### ISSUE TITLE
shm:get_keys(0) drives up cpu 100% blocks nginx worker for many seconds

### ISSUE THREAD

**Issue by davidbirdsong** [knyar/nginx-lua-prometheus#1]
At least for a prometheus instance containing 20k distinct metric keys.

I'll ask around, but I wonder if there are any tricks w/ FFI that would give us the list of keys as an iterator so that we could call get_key without asking the shm for the whole key space.

**Comment by knyar** [comment]
Yeah, `get_keys()` locks the dict, so might not only block the worker listing the keys, but also other workers that try to write to the dict. With current implementation if you need to have that many metrics, you should be comfortable with these sort of stalls during collection. I probably need to document this in the README.

Since adding a new metric is a relatively rare operation, instead of naively listing the dictionary during collection we could keep the list of metrics on the side - for example, under a separate key in the same dictionary. This will, however, require serializing that list into a string (I wonder what the maximum size of a string value is) and somehow coordinating write access to that key by multiple workers.

This does not look too elegant, so perhaps a better solution for such use case might be to use an external metric storage instead of the dict (lua-resty-redis?) or write a native C module for tracking the metrics.

Apologies that I could not be more helpful.
