### ISSUE TITLE
Can You help me?

### ISSUE THREAD

**Issue by godjil** [knyar/nginx-lua-prometheus#11]
Could you help me export Referers?

**Comment by knyar** [comment]
Are you looking to add `Referer` as a metric dimension? Just define a new metric field and populate it based on nginx variables, similarly to how README.md does with the `Host` header.

However, please keep in mind that using unmodified `Referer` will significantly increase metric cardinality, so you might see excessively large number of metrics in built-in dictionary. See *Caveats* section in README for more details. Instead of using `Referer` verbatim, I would suggest extracting just the minimum necessary information (for example, only the domain name).
