### ISSUE TITLE
anyway to skip endpoint '/metrics' from counter, histogram and gauge

### ISSUE THREAD

**Issue by ariefMudahMy** [knyar/nginx-lua-prometheus#113]
Hi, 
i've been using nginx_lua_prometheus, since then it really working great
thank you for sharing this.

i have a question for you, what if we want to skip traffic to endpoint '/metrics'
from any metrics number? ii know its small number compare to real traffic, 
but we put prometheus to scrape every 1 minute, and we want to remove
that /metrics number from any number in the prometheus.

any hint on how to do this?

thank you for you answer

**Comment by knyar** [comment]
I am assuming this is happening because you increment some metrics globally for all servers in the `http` section?

You can either move `log_by_lua_block` from the `http` section into the specific `server` section, or skip incrementing metrics for requests that come to the metric collection endpoint (for example, by exiting early in `log_by_lua_block` if `ngx.var.server_port` equals to 9145, assuming you use 9145 as your metric collection port).
