### ISSUE TITLE
overhead

### ISSUE THREAD

**Issue by behnambm** [knyar/nginx-lua-prometheus#128]
When i add the configs to `nginx.conf` and start nginx It uses 100% of CPU.

**Comment by knyar** [comment]
Thank you for filing an issue. Unfortunately I am going to have to close it, because it's not really clear that the behaviour you are seeing is caused by this library. If you think you have discovered a bug in the library, please feel free to submit a PR with a fix, or at least a detailed description of the bug along with the steps necessary to reproduce it.
