### ISSUE TITLE
nginx is getting uninstalled after installing `libnginx-mod-http-lua`

### ISSUE THREAD

**Issue by ghost** [knyar/nginx-lua-prometheus#129]
I'm using docker hub image (nginx:1.21.0) to install nginx.

After running following command to install  `libnginx-mod-http-lua`.
`apt-get install  libnginx-mod-http-lua=1.14.2-2+deb10u4`

Installation was successfull, but somehow nginx package is getting replaced/removed

Is `libnginx-mod-http-lua` module is not compatible with `nginx:1.21.0` ?

**Comment by dolik-rce** [comment]
Nginx modules must be always built with the same version of nginx, otherwise they wouldn't work. That is why the package manager removes the nginx, because it is not compatible with the module.

So if you're using nginx 1.21.0, then you should install (or build) `libnginx-mod-http-lua 1.21.0` to ensure compatibility.

**Comment by ghost** [comment]
Hi @dolik-rce. Thanks for the reply.
I'm unable to find `libnginx-mod-http-lua 1.21.0` version. Could you please help me with link.

**Comment by dolik-rce** [comment]
Sorry @rajism, but I can't. I'm not using Ubuntu (or Debian or whatever the image is based on) and it is not even related to this library.

**Comment by knyar** [comment]
Thanks for jumping in, @dolik-rce! As usual, your help here is much appreciated!

@rajism, since the questions you are raising do not seem to be related to this library, I am going to close this issue. I know this might be frustrating, and hope that you will find a solution to the issue you are having. Good luck!
