### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by CyberLine** [knyar/nginx-lua-prometheus#135]
With latest master on debian 11 and nginx 1.18 i get the following error:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [error] init_by_lua error: /opt/nginx-lua-prometheus/prometheus.lua:736: no request object found
stack traceback:
        [C]: in function 'ngx_re_gsub'
        /opt/nginx-lua-prometheus/prometheus.lua:736: in function 'counter'
        /opt/nginx-lua-prometheus/prometheus.lua:668: in function 'init'
        init_by_lua:2: in main chunk
nginx: configuration file /etc/nginx/nginx.conf test failed
```

when rolling back the repo to commit to 275bf3e6f7570c3a929fbacc52f3047db3f8687a nginx is crashing with: `[alert] 1210628#1210628: worker process 2638284 exited on signal 11` when accessing port 9145

**Comment by knyar** [comment]
Thank you for your report! The first error seems new as `ngx_re_gsub` has been added recently in #131, so we should definitely investigate why that happened.

However seeing a process segfault (`... exited on signal 11`) hints that the issue might not actually be related to this library. We've seen a similar message caused by a broken lua module packaged in Ubuntu (#105), so I wonder if the same is happening on Debian now.

**Comment by CyberLine** [comment]
Well, to be clearify:
old setup:
- Debian 10, nginx 1.14 with 275bf3e6f7570c3a929fbacc52f3047db3f8687a was working.
- Debian 10, nginx 1.14 with master ended in `nginx: [error] init_by_lua error: /opt/nginx-lua-prometheus/prometheus.lua:736: no request object found`

new setup:
- Debian 11, nginx 1.18 with 275bf3e6f7570c3a929fbacc52f3047db3f8687a crashes with signal 11
- Debian 11, nginx 1.18 with master ended in `nginx: [error] init_by_lua error: /opt/nginx-lua-prometheus/prometheus.lua:736: no request object found`

**Comment by tzssangglass** [comment]
`ngx_re_gsub` is [ngx.re.gsub](https://github.com/openresty/lua-nginx-module#ngxregsub), what is a function in OpenResty.(should not be in the nginx native library)

This is a bit of a tricky problem. Because there are still performance issues with lua's string functions if we want to maintain compatibility with nginx.

**Comment by knyar** [comment]
Note that the latest `master` branch version seems to work fine on Debian 10 as evidenced by [the integration test](https://github.com/knyar/nginx-lua-prometheus/runs/4948141839?check_suite_focus=true). It does crash nginx on Debian 11, which is something we need to investigate.

@CyberLine, your first comment references `init_by_lua`, so I just wanted to confirm that you are initializing the library correctly in the `init_worker_by_lua_block` block rather than `init_by_lua_block`? This [has been necessary](https://github.com/knyar/nginx-lua-prometheus/blob/master/CHANGELOG.md#020200420) since 0.20200420. If that is not the issue, perhaps you could please share your configuration so that I could reproduce the "no request object found" error?

**Comment by CyberLine** [comment]
@knyar actual config:

```
load_module modules/ndk_http_module.so;
load_module modules/ngx_http_lua_module.so;

...

http {
    lua_shared_dict prometheus_metrics 10M;
    lua_package_path "/opt/nginx-lua-prometheus/?.lua;;";
    init_worker_by_lua_block {
      prometheus = require("prometheus").init("prometheus_metrics")
      metric_requests = prometheus:counter(
        "nginx_http_requests_total", "Number of HTTP requests", {"host", "status", "verb"})
      metric_latency = prometheus:histogram(
        "nginx_http_request_duration_seconds", "HTTP request latency", {"host", "status", "verb"})
      metric_connections = prometheus:gauge(
        "nginx_http_connections", "Number of HTTP connections", {"state"})
    }

    log_by_lua '
      metric_requests:inc(1, {ngx.var.server_name, ngx.var.status, ngx.var.request_method})
      metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name, ngx.var.status, ngx.var.request_method})
    ';

    server {
      listen 9145;

      location /metrics {
        content_by_lua '
          metric_connections:set(ngx.var.connections_reading, {"reading"})
          metric_connections:set(ngx.var.connections_waiting, {"waiting"})
          metric_connections:set(ngx.var.connections_writing, {"writing"})
          prometheus:collect()
        ';
      }
    }
}
```

so still getting signal 11

**Comment by knyar** [comment]
OK, so crashing with signal 11 seems to unfortunately be expected on Debian 11, since they packaged `ngx_lua` version 0.10.13 that [is not compatible](https://github.com/openresty/lua-nginx-module/tree/v0.10.13#nginx-compatibility) with nginx 1.18. I have been able to reproduce a crash on Debian 11 without using `nginx-lua-prometheus` at all, and found an already existing bug reported to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994178

**Comment by knyar** [comment]
> @knyar actual config:

Thank you for sharing it. I [used this config](https://github.com/knyar/nginx-lua-prometheus/tree/repro_135) with the latest `master` branch commit on Debian 10 and could not reproduce the "no request object found" error: https://github.com/knyar/nginx-lua-prometheus/runs/4948694640

Any thoughts on what the difference might be?

**Comment by CyberLine** [comment]
> > @knyar actual config:
> Any thoughts on what the difference might be?

I'am on Debian 11 now, thats the difference...
> nginx: [error] init_by_lua error: /opt/nginx-lua-prometheus/prometheus.lua:736: no request object found

this was the old config with init_by_lua ... with the correct syntax there is just the signal 11 left over

**Comment by knyar** [comment]
> this was the old config with init_by_lua ... with the correct syntax there is just the signal 11 left over

Understood, thanks for confirming.
