### ISSUE TITLE
screenshot on grafana.net/dashboards

### ISSUE THREAD

**Issue by bbigras** [knyar/nginx-lua-prometheus#16]
A screenshot on https://grafana.net/dashboards would be great.

**Comment by knyar** [comment]
Not sure I understand what you mean. This library has nothing to do with Grafana and has no UI.

**Comment by rbosneag** [comment]
apparently there is a Grafana Dashboard mentioning your exporter [here](https://grafana.com/dashboards/462). People are asking how to use it (including myself). Now I assume we have to configure our own dashboards, which is fine, but that's the reason of the initial question.

**Comment by knyar** [comment]
Ah, gotcha. I think you should contact the author of that dashboard if you have any questions.

Given that each organization is likely to have their own schema for Prometheus labels, I am not particularly optimistic about Grafana dashboards being reusable. The dashboard you referenced seems to require metrics to have a label called "role". Other deployments might call the same concept a "group" or a "tier". You might also be interested in per-server, or per-virtualhost metrics rather than per-"role". I think monitoring dashboards are so use-case-specific, that the best approach is to design and implement ones yourself making them fit your specific needs and requirements.
