### ISSUE TITLE
why is there no `del` method for `histogram` types

### ISSUE THREAD

**Issue by juststillthinking** [knyar/nginx-lua-prometheus#165]
The `counter` and `gauge` has `del` method, however the `histogram` doesn't have one, how can i delete a particular metric that are `histogram`?

**Comment by knyar** [comment]
The primary reason is because deletion does not happen atomically, and deleting histogram counters will race with metric collection, potentially resulting in inconsistent data being scraped by prometheus, with some counters that are part of the histogram metric being present, but some already deleted.

I am open to contributions that aim to address this. Incrementing histogram counters is also racey with metric collection, which was the reason behind #161. If you have ideas on improving this and time to implement them, I'd be happy to discuss them and review the PR(s).
