### ISSUE TITLE
how to clear metric after collect()?

### ISSUE THREAD

**Issue by jils2013** [knyar/nginx-lua-prometheus#22]
do ngx.shared.DICT:flush_all()？ any advice？

**Comment by knyar** [comment]
You would normally not need to do this (unless you have high churn of label values and would like to remove old unused metric+label combinations), but yes, `flush_all()` should remove all items from the dictionary. Also keep in mind that this could result in some data loss, since there might be other threads updating the metrics between collection and the time `flush_all` is called.

**Comment by jils2013** [comment]
Any function or argment in nginx-lua-prometheus can do this operation safely？i mean clear metric or reset metric value ...

**Comment by knyar** [comment]
No. Since you would normally not need to do this, it's not something that's provided by nginx-lua-prometheus.

**Comment by jils2013** [comment]
Many thanks for your reply.

**Comment by phanama** [comment]
Why would we not normally do this? Does the ngx.shared.DICT has some kind of auto-flushing and auto-staling data?

**Comment by knyar** [comment]
There is no auto-flushing.

You would not normally want to reset metrics after collection because there's often multiple Prometheus servers collecting metrics from the same job (for redundancy). Also, even though Prometheus handles counter resets correctly, counters are designed to be incremented until process restarts.

The only case when you'd want to flush the list of metrics is when you are renaming them or otherwise doing active development. In that case you can just restart the nginx process.

**Comment by phanama** [comment]
So what would happen if the shared memory gets full?

**Comment by knyar** [comment]
There is a separate dictionary entry for each unique combination of _metric name + metric labels_, so its size grows proportionally to the number of metrics and labels, rather than to the number of events that increment those metrics.

If the dictionary gets full you should see error log messages and `nginx_metric_errors_total` counter incremented (this is not checked by automatic tests). For a reasonably large dictionary size, that will only happen when you have excessive number of metrics or label value combinations, which is [a bad idea](https://github.com/knyar/nginx-lua-prometheus#caveats) anyway.
