### ISSUE TITLE
How serious Caveats are?

### ISSUE THREAD

**Issue by zevarito** [knyar/nginx-lua-prometheus#4]
Hi,

I am experimenting with `Nginx-Lua` and so far so good but with some issues that might be caused by a misunderstanding from my side. First of all I am tracking API `endpoints` for each server/app, I guess that should not be a good practice since the cardinality is to high because some URL's are namespaced with user_ids. So I wonder how can I get metrics/alerts from slow endpoints and other information without actually storing endpoint hits.

By the other side for some `Nginx-Lua` jobs I am getting: `net/http: request canceled` as result of Prometheus Job. I've increased the timeout in Prometheus to 15s, same result, I don't think I have to allow the scrape to take forever so, what actually could be causing this and which is the best way to solve it?

Thanks!

**Comment by zevarito** [comment]
I forget to paste log from nginx access error side. But I don't think is related to the timeout/canceled request at all.

```
2016/09/21 12:00:31 [error] 9188#9188: *103246 [lua] prometheus.lua:236: log_error(): Wrong number of labels for nginx_http_requests_total. Expected 5, got 3 while logging request, client: 169.229.3.91, server: , request: "<?X{N<????ƯI)ƅ??h??;8^??xZt].   v??Bh?Q"
```

**Comment by knyar** [comment]
If you have too many label values, I would imagine fetching all of them might take so long that Prometheus will time out.

The error message you posted indicates that you are trying to increment a metric with the wrong number of label values: you declared 5 labels, but only provided values for 3.

Do you think you could share your nginx configuration via https://gist.github.com/?

**Comment by zevarito** [comment]
@knyar Here is the gist: https://gist.github.com/zevarito/698bbd189d3ec7f0551bff0b578aafde

Yes, totally, the error is actually very descriptive but I couldn't find the cause yet.

What do you think is an acceptable timeout ?

**Comment by knyar** [comment]
I think the default timeout should work well in most cases. I would definitely suggest dropping the "uri" label, or looking for a way to decrease its cardinality – for example, by using the first part of the request path rather than the full path ('/foo' for 'http://example.com/foo/bar'). Keep in mind that ngx.var.host can also produce quite a lot of values for the default virtualhost of a server directly exposed to the internet, since many people do HTTP scans with bogus `Host` headers. In production I would suggest using a meaningful site identifier hard-coded in nginx configuration instead of ngx.var.host.

It's hard to tell where the label value count mismatch error came from. Do you have a way to reliably reproduce it?

**Comment by zevarito** [comment]
@knyar Notice I am using a custom `app` variable, each of server configuration defines that variable so I think  I just can get rid of host and use `app` variable.

I've updated to Prometheus `master` today and suddenly no more requests canceled.

Thanks for your help.

**Comment by zevarito** [comment]
@knyar what about gzip to reduce metrics response time?

**Comment by knyar** [comment]
I'd check how long it takes to fetch metrics from nginx locally via localhost, and if it takes a long time as well, then I don't think gzip will make any difference unless you are bandwidth-constrained.
