### ISSUE TITLE
Compute Rate-Per-Second

### ISSUE THREAD

**Issue by 5agado** [knyar/nginx-lua-prometheus#44]
First of all thanks for the great tool!

Wanted to ask if there is any way to obtain rate-per-second for counter metrics, as it would be useful to operate continuous monitoring on REST APIs and to properly computer success/failure rates.

Optimally even better if this are computed directly by this tool, so can be retrieved at the specified endpoint without the need of further tools or processing steps.

Like is there any way to even call Prometheus queries inside the Lua code?

**Comment by knyar** [comment]
The conventional way to obtain a rate is to collect metrics into a Prometheus server and use the `rate()` function. Reimplementing the same functionality inside the lua library will require it to store a time series instead of simply maintaining a counter.

I'd recommend you to use a Prometheus server for this. In any case, you will need _something_ that will collect this sort of telemetry from multiple instances of nginx, and Prometheus server is the right tool for that job (and will also give you back a rate).
