### ISSUE TITLE
Including path as a label without high cardinality issues

### ISSUE THREAD

**Issue by bghellofresh** [knyar/nginx-lua-prometheus#47]
First of all, thank you for this extension. It's been very useful for my use case.

I would like to include path information in our metrics output to gain a more granular understanding of the traffic in our distributed application environment. In Issue #29 it was mentioned that `ngx.var.uri` could be used for a related use case to collect metrics for a specific endpoint. 

Since I would like to offer a centralised solution for application services in our system, I would ideally add the path as a label but am concerned about cardinality issues that would arise as a result. For example, many uris would contain unique identifiers that would initiate the creation of too many time series for a single metric and risk overloading prometheus instances as a result. 

It would be useful if there were a method that would allow including path that imposed limits on possibly high cardinality values. Any suggestions would be greatly appreciated.

**Comment by sztanpet** [comment]
You could just write a bit of simple lua to handle known paths with unique ids, and deduplicate/ignore 404-s, Doing this generically, now that is hard

**Comment by knyar** [comment]
I see two possible ways you can approach this:
1. manually limit the range of possible values of the path variable by modifying it. For example, instead of using the full path, just use a prefix that is mostly static - i.e. `example.com/users/info/1323` results in `path_prefix="/users/info"`. Similarly, you can hard-code a list of URLs that might contain unique identifiers and strip them.
2. automatically decrease the range of possible values. A typical way to do this is to use hashing. For example, you can use something like `ngx.crc32_short(ngx.var.uri) % 10` to hash the URI into a number between 0 and 9, and then use that number as a label variable - i.e. `example.com/v1/status` will result in `path_hash="5"`.

With the second approach there is obviously no way to get a list of all URLs hashed to a particular hash value, however you can determine what a specific URL will hash to. Such approach is useful to determine whether an increase in latency (or errors) affects all URLs or just one of them: if you are seeing increased latency for only a single hash bucket, the problem likely only affects a single URL.

I hope this helps.
