### ISSUE TITLE
How to collect multiple indicators？

### ISSUE THREAD

**Issue by gouki777** [knyar/nginx-lua-prometheus#61]
hello 
i want collect multiple indicators. for host uri and status.
my config,but the configuration seems to be wrong. it's bad.
```
    log_by_lua '
    metric_requests:inc(1, {ngx.var.host, ngx.var.status})
    metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.host}, {ngx.var.uri}, {status})
    ';
```
I read the prometheus.lua;
Prometheus :histogram of just one metric?
```
    metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
```
so,How to collect multiple indicators？
can you help me,thanks.

**Comment by knyar** [comment]
The number of label values you provide should match the number of labels you defined while creating a metric.

If you are looking to do:
```
metric_latency:observe(
  tonumber(ngx.var.request_time), {ngx.var.host}, {ngx.var.uri}, {status})
```

You will need to define the metric with labels for URI and status; for example:
```
metric_latency = prometheus:histogram(
  "nginx_http_request_duration_seconds", "HTTP request latency",
  {"host", "uri", "status"})
```

Note, if you are planning to use this sort of configuration in production, I would discourage you from using URI as one of the labels, since it increases metric cardinality. This can [result in nginx stalls while metrics are collected](https://github.com/knyar/nginx-lua-prometheus#large-number-of-metrics) and is generally not supported well by Prometheus.

**Comment by gouki777** [comment]
Thank you for your help.I will shrink the label
