### ISSUE TITLE
Increasing the number of nginx worker_processes

### ISSUE THREAD

**Issue by syedmhashim** [knyar/nginx-lua-prometheus#71]
I'm just wondering how would it affect the prometheus metrics collection if I increase the number of worker_processes. From what I understand each worker_process is a seperate thread. So would each of the worker_processes collect there own metrics and how would prometheus scrape all of them?

**Comment by dolik-rce** [comment]
There is not much difference if you use more workers. There is always only one shared dict holding the metrics for all worker processes. It's implementation is pretty fast when adding/increasing metrics.

The only trouble is when the metrics are collected (since it blocks all workers, see the note [in docs](https://github.com/openresty/lua-nginx-module#ngxshareddictget_keys)), but that is not proportional to number of workers, only to total number of timeseries.

**Comment by syedmhashim** [comment]
Okay got it. Thanks!
