### ISSUE TITLE
Unexpected nil value for label error was removed

### ISSUE THREAD

**Issue by dav-is** [knyar/nginx-lua-prometheus#81]
https://github.com/knyar/nginx-lua-prometheus/blob/cb27be9e40d3d63116fc228def94c86fd1b3e269/prometheus.lua#L212
no longer has https://github.com/knyar/nginx-lua-prometheus/blob/b7c8feb69a17253ead904d1beee98d4625a533ab/prometheus.lua#L79-L81

Causing:
`/usr/local/share/lua/5.1/prometheus.lua:214: table index is nil`

**Comment by knyar** [comment]
This is surprising, since the [label count check](https://github.com/knyar/nginx-lua-prometheus/blob/cb27be9e40d3d63116fc228def94c86fd1b3e269/prometheus.lua#L199) in the beginning of that function is supposed to catch `nil` values, and there [are tests for that](https://github.com/knyar/nginx-lua-prometheus/blob/cb27be9e40d3d63116fc228def94c86fd1b3e269/prometheus_test.lua#L169) that are passing.

Any idea why it might be failing for you? Could you provide a test case, or share your metric definition and code that changes metric value?

**Comment by knyar** [comment]
@dav-is, given that nobody else seems to be seeing this problem, I will assume this is something specific to your environment and will close this issue now. If you think there is something wrong with the library, please feel free to reopen it and provide more details. Thanks!
