### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by dolik-rce** [knyar/nginx-lua-prometheus#92]
Hi, I just noticed there is a typo in the value of `ERR_MSG_COUNTER_NOT_INITIALIZED`.

Also, while fixing it, we could make the message more helpful. I think by far the most common reason to see this message is that the programmer forgot to call `init_worker`. So maybe something like this would be nice:
```lua   
local ERR_MSG_COUNTER_NOT_INITIALIZED = "Counter not initialized, did you call init_worker?"
```

**Comment by knyar** [comment]
Sounds like a good plan.

In general it's pretty inconvenient that module initialization is split across two hooks (`init_by_lua` and `init_worker_by_lua`). I am curious whether we can just move all initialization into `init_worker_by_lua` to make things a bit simpler. This will make each worker independently create metrics, but since all workers will use the same configuration, I think everything should still work OK.

**Comment by dolik-rce** [comment]
I have actually found one more scenario where this message appears: When you try to set a histogram or counter in `init_by_lua*` block. Moving all the initialization code to workers would solve this as well. It would also be more user friendly, since we could use the metrics right after they're created.
