### ISSUE TITLE
Is there any plan to support prometheus push?

### ISSUE THREAD

**Issue by qichengzx** [knyar/nginx-lua-prometheus#93]
Are you planning to support push metrics to pushgateway in near future?

If no, We have such a requirement in our current scenario, and I have completed this function myself, can I submit a PR?

**Comment by dolik-rce** [comment]
Why would you prefer pushgateway, when you can use scraping? Pushgateway has many problems and limitations and is only recomended for service-level batch jobs. See the official docs: https://prometheus.io/docs/practices/pushing/ for more details.

I'm not a maintainer of this module, but my personal opinion is that pushing should not be supported, since it would promote improper use of Prometheus.

**Comment by qichengzx** [comment]
@dolik-rce Yes, in our scenario, it was originally planned to use pull mode, but due to the stability of some basic services, the IP list of service instances could not be sensed in time and accurately, and no other services can use such as consul, dns, So we are going to use push mode for data reporting.

**Comment by knyar** [comment]
I have no plans to implement push, and I agree that we probably should not make it part of the library. It's not trivial to do it in a clean way, especially when you consider that `del` and `reset` will have to make out outbound HTTP requests to remove metrics from pushgateway.

What I would suggest you do is just add a separate process that will regularly scrape metrics from nginx and push them to the pushgateway. If you don't delete metrics from nginx, this can be as simple as `curl -s localhost:9145/metrics | curl -s --data-binary @- http://pushgateway/metrics/job/nginx/instance/$(hostname)`
